### ISSUE TITLE
Weapon Stay GameSetting not respected

### ISSUE THREAD

**Issue by PhasecoreX** [Deaod/VoteSys#10]
It seems that when I set `GameSettings=bCoopWeaponMode=False` in a preset, it doesn't get applied to the game (weapons still stay after picking them up). I am pretty sure that this is the setting for controlling if weapons stay, as it's the only one that changes in my local UnrealTournament.ini file when I check and uncheck "Weapons Stay" in UT.

**Comment by Deaod** [comment]
`bCoopWeaponMode` controls weapon stay in single-player games and for gamemodes not based on DeathMatchPlus. If youre hosting a multiplayer match and the gamemode is based on DeathMatchPlus, you should use `bMultiWeaponStay`.

**Comment by PhasecoreX** [comment]
Oh! Now I feel silly. Yes that one works correctly. I thought I tested that setting, but I guess not. Thank you!

Also, thank you for working on this mutator! Very well made, runs super smoothly, and it's been fun coming up with a bunch of presets with inheritance of settings and mutators. Makes things very easy to manage! :)
