### ISSUE TITLE
MinimumMapRepeatDistance > 0 Prevents Voting on New Presets

### ISSUE THREAD

**Issue by PhasecoreX** [Deaod/VoteSys#16]
I haven't dug too deep into it, but it seems that when `MinimumMapRepeatDistance` is more than 0, it disables selecting any maps in presets that haven't ever been used (not in the `VoteSysHistory.ini` I assume).

Code in question is `VS_PlayerChannel.uc`, line 266:

https://github.com/Deaod/VoteSys/blob/65561eea3a7a03769f86160fd81a0b63725dc70e/Classes/VS_PlayerChannel.uc#L263-L268

`P.MinimumMapRepeatDistance` is `MinimumMapRepeatDistance`, which would be non-zero.
Both `P.MaxSequenceNumber` and `M.Sequence` are zero for newly used presets, so this always returns, not allowing any maps to be selected.

I've only tested with `MinimumMapRepeatDistance` being 1, not sure what larger numbers would do...

**Comment by Deaod** [comment]
Excellent report. Thank you.

This was an oversight by me when i wanted to enforce the repeat distance server-side. It used to only be enforced client-side.

A maps Sequence number is always >0 if it has been voted at least once. Any map that has never been voted has Sequence number 0.

I think it should be fixed now, reopen this issue if it isnt.

**Comment by PhasecoreX** [comment]
Looks good, thank you!
