### ISSUE TITLE
Assault Defend Phase Skipped

### ISSUE THREAD

**Issue by PhasecoreX** [Deaod/VoteSys#25]
Hello again!

I could just be missing some config value or something, but for assaults, the vote menu pops up after the attack phase of the match. This prevents it from automatically going to the defend phase.

I know that XMaps has a "Don't interrupt Assault games" checkbox in the Game Switching options, if that helps at all.

**Comment by Deaod** [comment]
Can you try the latest version to confirm that if MultiRoundGameModes contains Botpack.Assault (or Assault), Assault works as expected?

**Comment by PhasecoreX** [comment]
I added `MultiRoundGameModes=Botpack.Assault` to my `VoteSys.ini` file, and it does go to the defend phase after finishing the attack phase without popping up the vote menu. However, a few seconds after the defend portion loads (spectating before the match) it switches gametypes and maps on it's own back to the default gametype (`DefaultPreset`).

If you mid-game vote back to an assault map, it starts the red team as defenders for some reason.

**Comment by Deaod** [comment]
I hope ive fixed both issues with the latest version. Can i trouble you to check once more?

**Comment by PhasecoreX** [comment]
Looks like both of those issues are fixed. The game moves onto the defending phase after attacking, and if I mid-game vote during the defending phase to another assault, it does start as attacking.

One last issue though, after the defend phase finishes, the vote menu does not pop up automatically. There's no "one minute remaining" voice message from VoteSys either, and after less than a minute it'll just automatically switch to another assault map (maybe the built in "Auto Change Levels" is doing this?)

**Comment by PhasecoreX** [comment]
Hmm... it also seems that whenever I first start the server and then map vote over to an assault, it always starts red on the defending team. Voting again will then correctly start on the attacking side. And it seems that every vote afterwards, to and from an assault match, will always start assault matches with red attacking. So there's something weird about the first `MultiRoundGameModes` match played since server startup.

**Comment by Deaod** [comment]
Hey, do you have time to give this another try?

**Comment by PhasecoreX** [comment]
Of course! It looks like the vote menu auto closes now, so I will close out that issue. For this issue:

- [x] After the assault phase, it doesn't pop up the vote menu, so that's now good.
- [x] Defend phase is allowed to play out, that's good.
- [ ] After the defend phase, the vote menu does not automatically pop up, and after waiting maybe 15 seconds (less than the VoteTimeLimit), it will go to the first map alphabetically (internal UT map list?).
- [x] Switching over from a non-assault over to an assault will start the red team attacking, so that's good
- [x] Switching to another assault map after only doing the attack phase of an assault will also start red attacking, which is good.

I think it's just that one last issue.

**Comment by Deaod** [comment]
First, thanks for checking it out once more and describing the issue so well.
Second, i did not mean to edit your comment, i didnt realize clicking the checkboxes would edit it.
Third, ive hopefully fixed the remaining issue with Assault.

**Comment by PhasecoreX** [comment]
You're welcome! Yeah the checkmarks are weird, I probably should have used emojis or something.

An assault match, attack and defend, works correctly and the vote menu pops up after the defend phase!

Something weird happened one time though, the very first test I did on AS-Bridge. After defending successfully, I voted for another assault map. The console started getting spammed with `Loading map  failed, randomly selecting ` (there are two spaces between "map" and "failed", probably a map name goes there) and the server log repeated these lines over and over:
```
MutVoteSys AS-Bridge.MutVoteSys0 (Function VoteSys.MutVoteSys.CheckVotedMap:005F) Accessed None 'VotedMap'                                                                                                         
MutVoteSys AS-Bridge.MutVoteSys0 (Function VoteSys.MutVoteSys.CheckVotedMap:0073) Accessed None 'VotedPreset'                                                                                                      
MutVoteSys AS-Bridge.MutVoteSys0 (Function VoteSys.MutVoteSys.CheckVotedMap:0096) Accessed None 'VotedMap'                                                                                                         
RPC bunch overflowed                                                                                                                                                                                               
MutVoteSys AS-Bridge.MutVoteSys0 (Function VoteSys.MutVoteSys.CheckVotedMap:0010) Accessed None 'VotedMap'                                                                                                         
MutVoteSys AS-Bridge.MutVoteSys0 (Function VoteSys.MutVoteSys.CheckVotedMap:0034) Accessed None 'VotedMap'                                                                                                         
 failed to load
```
I killed the server and restarted it, went back into an assault match, and... I haven't been able to reproduce that error. I've done assault matches, voted to both assault and non-assault matches after; that works fine. I've voted away from the defend portion of an assault match, works just fine as well. So I don't know what happened there...

Also after that first and only crash, when I restarted the server and voted back to an assault, it started on defend mode for the red team, but ever since then I can't reproduce that issue either, it always starts on attack.

So I guess this is good now? Thank you!

**Comment by Deaod** [comment]
> ever since then I can't reproduce that issue

I presume thats because the error happens when voting as admin. Either way, thanks for letting me know again and i hope i finally have this figured out.

**Comment by PhasecoreX** [comment]
Ah, yeah that makes sense. I was in admin mode while messing with another mutator. With your latest change seems that is fixed too.

Yeah this all looks good now, thank you again! I'll let you know if anything else comes up, but as far as I can tell we are all good :)
